[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    tooling: Tests specifically targeting the Maestro AI toolchain infrastructure.
    product: Standard FastAPI product tests.
    integration: Tests interacting with external APIs or DBs.
    e2e: End to End interface tests.
