"""
Configuration management commands.
Allows runtime configuration of API settings.
"""
import os
import click
from pathlib import Path
from config import Config
from utils import print_success, print_info
from rich.console import Console

console = Console()


@click.group(name="config")
def config_group():
    """Configuration management commands."""
    pass


@config_group.command(name="set")
@click.option("--api-url", help="Set API base URL (e.g., http://localhost:8000)")
@click.option("--api-key", help="Set API authentication key")
def set_config(api_url: str, api_key: str):
    """Configure TUI client settings.
    
    Sets configuration in the .env file in the TUI directory.
    These settings override environment variables.
    
    Examples:
        # Set API URL
        python main.py config set --api-url http://localhost:8000
        
        # Set API key
        python main.py config set --api-key your-secret-key
        
        # Set both
        python main.py config set --api-url http://api:8000 --api-key mykey
    """
    if not api_url and not api_key:
        raise click.UsageError("Please provide at least one configuration option (--api-url or --api-key)")
    
    # Determine .env file path (in TUI directory)
    tui_dir = Path(__file__).parent.parent
    env_file = tui_dir / ".env"
    
    # Read existing .env content
    env_content = {}
    if env_file.exists():
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_content[key.strip()] = value.strip()
    
    # Update configuration
    updated = []
    if api_url:
        env_content["API_BASE_URL"] = api_url
        updated.append(f"API_BASE_URL={api_url}")
        print_success(f"API URL set to: {api_url}")
    
    if api_key:
        env_content["API_KEY"] = api_key
        updated.append("API_KEY=***")  # Don't display the key
        print_success("API key configured")
    
    # Write updated .env file
    with open(env_file, "w") as f:
        f.write("# TUI Client Configuration\n")
        f.write("# Generated by 'config set' command\n\n")
        for key, value in env_content.items():
            f.write(f"{key}={value}\n")
    
    print_info(f"Configuration saved to: {env_file}")
    print_info("Configuration will be loaded on next TUI execution")


@config_group.command(name="show")
def show_config():
    """Display current configuration settings."""
    console.print("\n[bold cyan]Current Configuration[/bold cyan]\n")
    console.print(f"[bold]API Base URL:[/bold] {Config.API_BASE_URL}")
    console.print(f"[bold]API Timeout:[/bold] {Config.API_TIMEOUT} seconds")
    
    if Config.API_KEY:
        # Show only first/last 4 chars of API key, ensure proper masking
        key_len = len(Config.API_KEY)
        if key_len <= 8:
            masked_key = "***"
        else:
            masked_key = f"{Config.API_KEY[:4]}...{Config.API_KEY[-4:]}"
        console.print(f"[bold]API Key:[/bold] {masked_key}")
    else:
        console.print(f"[bold]API Key:[/bold] [dim]Not configured[/dim]")
    
    # Check if .env file exists
    tui_dir = Path(__file__).parent.parent
    env_file = tui_dir / ".env"
    
    if env_file.exists():
        console.print(f"\n[dim]Config file: {env_file}[/dim]")
    else:
        console.print(f"\n[dim]No .env file found. Using environment variables or defaults.[/dim]")


@config_group.command(name="reset")
@click.confirmation_option(prompt="Are you sure you want to reset configuration?")
def reset_config():
    """Reset configuration to defaults (removes .env file)."""
    tui_dir = Path(__file__).parent.parent
    env_file = tui_dir / ".env"
    
    if env_file.exists():
        env_file.unlink()
        print_success("Configuration reset successfully")
        print_info(".env file removed. Using environment variables or defaults.")
    else:
        print_info("No configuration file found. Already using defaults.")
