"""PlannerAgent — consumes GitHub issues and writes a plan to agent-bus.

Always uses a premium model (gpt-4o) regardless of complexity.
Currently a basic stub until semantic file context is fully added (Issue M-2).

Implements: Phase 1 multi-model tiering (Issue M-1)
"""

from __future__ import annotations

import os
from typing import Any, Optional, TYPE_CHECKING
from pathlib import Path

if TYPE_CHECKING:
    from openai import AsyncOpenAI
    from agents.mcp_client import MCPMultiClient


class PlannerAgent:
    """Creates execution plans for MAESTRO using premium models."""

    def __init__(
        self,
        mcp_client: "MCPMultiClient",
        model_tier: str = "full",
        llm_client: Optional["AsyncOpenAI"] = None,
        workspace_root: Optional[Path] = None,
    ) -> None:
        self._mcp = mcp_client
        self._model = "gpt-4o"  # Enforce premium model for planning
        self._root = workspace_root or Path.cwd()
        
        # We would lazily initialize openai client here if needed
        # self._llm = llm_client or ...
        
    async def run(self, run_id: str, issue_body: str) -> None:
        """Read issue and write a high-level plan into the bus run context."""
        # For M-1, we just create a placeholder plan. M-2 will add MCP tools.
        
        # In a real implementation:
        # 1. Fetch current run details from bus
        # 2. Use LLM to devise step-by-step plan
        # 3. Save tasks/plan back to bus
        
        plan_text = f"Initial Execution Plan for run {run_id}:\n1. Analyze requirements\n2. Modify files\n3. Run tests\n\n(Generated by {self._model} Planner)"
        
        try:
            # We assume bus has a way to update arbitrary memory or run context
            # For now, we will simply mock this via bus_set_status or similar if needed.
            # Mcp bus might naturally accept patches later.
            await self._mcp.call_tool(
                "bus_set_status",
                {"run_id": run_id, "status": "planning"}
            )
            
            # TODO: M-2 will formalize the JSON sub-tasks.
            
            await self._mcp.call_tool(
                "bus_set_status",
                {"run_id": run_id, "status": "coding"}
            )
        except Exception as e:
            # Best effort for the stub
            pass

